### ISSUE TITLE
Version key vereist

### ISSUE THREAD

**Issue by imathijs** [remco770/garbage-bar-homeassistant#10]
Na de update van HA 2021.4.0 zag ik dit in het log. Moest het even melden. Cheers.

Logger: homeassistant.loader
Source: loader.py:786 
First occurred: 9:23:59 PM (2 occurrences) 
Last logged: 9:23:59 PM

No 'version' key in the manifest file for custom integration 'bar_afvalbeheer'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'bar_afvalbeheer'

**Comment by jjvandenberg** [comment]
Yep: you need to add a version to the manifest.json, otherwise it won't load in Ha 2021.6

**Comment by remco770** [comment]
Fixed in release 1.4
