### ISSUE TITLE
Overige types afval werken niet

### ISSUE THREAD

**Issue by search-tool** [remco770/garbage-bar-homeassistant#4]
Gemeente Ridderkerk en Albrandswaard hebben wel restafval, PMD en andere verzameling.
Om de sensors compleet voor deze gemeentes is het beter om GREY, PACKAGES etc er aan toe te voegen.

Thx for the work!

**Comment by harisosmancevic** [comment]
In Ridderkerk heb ik inderdaad ook restafval dat opgehaald wordt, zou fijn zijn om die er ook tussen te hebben..

**Comment by remco770** [comment]
#6

**Comment by remco770** [comment]
#7 Adding PMD

**Comment by remco770** [comment]
@search-tool @harisosmancevic Willen jullie nogmaals testen?
