### ISSUE TITLE
Update info on HACS page

### ISSUE THREAD

**Issue by harisosmancevic** [remco770/garbage-bar-homeassistant#5]
The HACS pages gives this configuration.yaml example:

sensor:
  - platform: bar_afvalbeheer
    postcode: 0000AA
    housenumber: 1
    resources:
      - today
      - tomorrow
      - grey
      - green
      - paper
      - packages

should be:

sensor:
  - platform: bar-afvalbeheer
    postcode: 0000AA
    housenumber: 1
    resources:
      - today
      - tomorrow
      - green
      - paper

**Comment by angeloloi** [comment]
Vraag: hoe zit het met restafval?

**Comment by harisosmancevic** [comment]
Die werkt bij mij helaas niet, lijkt eruit gehaald te zijn. Die mis ik ook..

**Comment by remco770** [comment]
#6 en #7 lossen dit op.
