### ISSUE TITLE
Geen papier informatie in Barendrecht

### ISSUE THREAD

**Issue by ashwin2101** [remco770/garbage-bar-homeassistant#8]
Beste sinds vorige week is er geen papier informatie zichtbaar. de melding is unknown
GFT is wel zichtbaar

Via de website: https://www.bar-afvalbeheer.nl/afvalkalender
is wel te zien dat het papier op maandag 29 juli wordt opgehaald.
Postcode: 2993 XN
huisnummer: 2 (niet mijn echte huisnummer)

**Comment by remco770** [comment]
Er is een nieuwe versie uit. Mocht je nog problemen hebben open een nieuw issue!
